repos:
  - repo: https://github.com/lorenzwalthert/precommit
    rev: v0.4.2
    hooks:
      - id: style-files
        args: [--style_pkg=styler, --style_fun=tidyverse_style]
      - id: roxygenize
        additional_dependencies:
          - jsonlite
          - httpuv
          - rstudioapi
          - shiny
          - miniUI
          - base64enc
      - id: lintr
        args: [--warn_only]
      - id: parsable-R
      - id: no-browser-statement
      - id: no-debug-statement
